config/routes.rb
# -*- encoding : utf-8 -*-
RhodesPc2::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'pages#landing'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  match "/pages/glenn", :id => 'glenn'
  match "/pages/heather", :id => 'heather'

  get "/admin" => 'admin/news#index'

  namespace :admin do
    resources :news
    resources :events
    resources :people
  end

  resources :news
  resources :events do
    member do
      get "download"
    end
  end
  resources :people
  
  resources :contacts do
    collection do
      post "send_form_information"
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :event_file, :will_publish_at
  validates_presence_of :title, :event_file
  scope :is_published, where("will_publish_at <= ?", Date.today)
  acts_as_url :title
  mount_uploader :event_file, PdfUploader

  def to_param
    url # or whatever you set :url_attribute to
  end

  def self.latest_ten
    last(10).reverse
  end

  def self.is_previous(month)
    month_begin = "#{Date.today.year}-#{month}-1".to_date
    month_end = month_begin.end_of_month
    where(:will_publish_at => month_begin..month_end)
  end

  def file_name
    event_file.original_filename
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "admin"
  before_filter :login_required
  before_filter :require_is_admin

  def index
    if params[:month].present?
      @month = params[:month]
    else
      @month = Date.today.month
    end
    @year = Date.today.year
    @events = Event.is_previous(@month)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])

    if @event.save
      redirect_to admin_events_path, :notice => "Event saved"
    else
      flash[:warning] = "Something went wrong :<"
      render :new
    end
  end

  def edit
    @event = Event.find_by_url(params[:id])
  end

  def update
    @event = Event.find_by_url(params[:id])

    if @event.update_attributes(params[:event])
      redirect_to admin_events_path, :notice => "Event Updated"
    else
      flash[:warning] = "Something went wrong :<"
      render :edit
    end
  end

  def destroy
    @event = Event.find_by_url(params[:id])
    @event.destroy

    redirect_to admin_events_path, :notice => "Event Deleted"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "bio"
  
  def index
    @events = Event.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
  end

  def show
    @file = Event.find_by_url(params[:id]).event_file.path
    send_file( @file, :disposition => 'inline', :type => "application/pdf")
  end

  def download
    @file = Event.find_by_url(params[:id]).event_file.path
    send_file @file
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/edit.html.erb
<div class="span10">
  <h3>Edit Event</h3>
  <%= simple_form_for([:admin, @event]) do |f| %>
  <%= f.input(:title) %>
  <%= f.input(:event_file) %>
  <%= f.input(:will_publish_at) %>
  
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_events_path, :class => "btn btn-warning") %>
  <% end %>
</div>

app/views/admin/events/index.html.erb
<div class="span10">

  <h3>Event List - <%= @month %> / <%= @year %></h3>
  <div class="btn-group">
    <%= link_to("Prev", admin_events_path(:month => @month.to_i-1), :class => "btn btn-info") %>
    <%= link_to("Next", admin_events_path(:month => @month.to_i+1), :class => "btn btn-info") %>
  </div>
  <%= link_to("Add Event", new_admin_event_path, :class => "btn btn-info pull-right") %>
  <br><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="200px">Title</th>
        <th width="120px">File</th>
      </tr>
    </thead>
    <% @events.each do |event| %>
    <tr>
      <td><%= link_to(event.title, event_path(event), :target => "_blank" ) %></td>
      <td>
        <%= link_to("Edit", edit_admin_event_path(event), :class => "btn btn-warning btn-small") %>
        <%= link_to("Delete", admin_event_path(event), :method => :delete, :confirm => "Are You Sure you want to delete ?", :class => "btn btn-danger btn-small") %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/events/new.html.erb
<div class="span10">
  <h3>Add Event</h3>
  <%= simple_form_for([:admin, @event]) do |f| %>
  <%= f.input(:title) %>
  <%= f.input(:event_file, :label => "Choose Event PDF (Max file size 10MB)") %>
  <%= f.input(:will_publish_at) %>
  
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_events_path, :class => "btn btn-warning") %>
  <% end %>
</div>