config/routes.rb
# -*- encoding : utf-8 -*-
RhodesPc2::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'pages#landing'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  match "/pages/glenn", :id => 'glenn'
  match "/pages/heather", :id => 'heather'

  get "/admin" => 'admin/news#index'

  namespace :admin do
    resources :news
    resources :events
    resources :people
  end

  resources :news
  resources :events do
    member do
      get "download"
    end
  end
  resources :people
  
  resources :contacts do
    collection do
      post "send_form_information"
    end
  end
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  author       :string(255)
#  content      :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  url          :string(255)
#  content_html :text
#

class News < ActiveRecord::Base
  attr_accessible :title, :author, :content, :will_publish_at
  validates_presence_of :title, :content
  scope :is_published, where("will_publish_at <= ?", Date.today)
  acts_as_url :title

  auto_html_for :content do
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  def self.latest_ten
    last(10).reverse
  end

  def to_param
    url # or whatever you set :url_attribute to
  end

  def self.is_previous(month)
    month_begin = "#{Date.today.year}-#{month}-1".to_date
    month_end = month_begin.end_of_month
    where(:will_publish_at => month_begin..month_end)
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  layout "admin"
  before_filter :login_required
  before_filter :require_is_admin
  
  def index
    if params[:month].present?
      @month = params[:month]
    else
      @month = Date.today.month
    end
    @year = Date.today.year
    @news = News.is_previous(@month)
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(params[:news])

    if @news.save
      redirect_to admin_news_index_path, :notice => "News saved"
    else
      flash[:warning] = "Something went wrong :<"
      render :new
    end
  end

  def edit
    @news = News.find_by_url(params[:id])
  end

  def update
    @news = News.find_by_url(params[:id])

    if @news.update_attributes(params[:news])
      redirect_to admin_news_index_path, :notice => "News Updated"
    else
      flash[:warning] = "Something went wrong :<"
      render :edit
    end
  end

  def destroy
    @news = News.find_by_url(params[:id])
    @news.destroy

    redirect_to admin_news_index_path, :notice => "News Deleted"
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout "bio"

  def show
    @news = News.find_by_url(params[:id])
  end

  def index
    @news = News.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
  end
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/news_helper.rb
module NewsHelper

  def render_news_title(news)
    news.title
  end

  def render_news_content(news)
    news.content_html
  end

  def render_news_author(news)
    news.author
  end
end

app/views/admin/news/edit.html.erb
<div class="span10">
  <h3>Edit News</h3>
  <%= simple_form_for([:admin, @news]) do |f| %>
  <%= f.input(:title) %>
  <%= f.input(:author) %>
  <%= f.input(:will_publish_at) %>
  <%= f.input(:content, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_news_index_path, :class => "btn btn-warning") %>
  <% end %>
</div>
<%= tinymce_assets %>
<%= tinymce theme: 'advanced' %>

app/views/admin/news/index.html.erb
<div class="span10">

  <h3>News List - <%= @month %> / <%= @year %></h3>
  <div class="btn-group">
    <%= link_to("Prev", admin_news_index_path(:month => @month.to_i-1), :class => "btn btn-info") %>
    <%= link_to("Next", admin_news_index_path(:month => @month.to_i+1), :class => "btn btn-info") %>
  </div>
  <%= link_to("Add News", new_admin_news_path, :class => "btn btn-info pull-right") %>
  <br><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="200px">Title</th>
        <th width="100px">Author</th>
        <th>Content</th>
        <th width="120px">Action</th>
      </tr>
    </thead>
    <% @news.each do |news| %>
    <tr>
      <td><%= link_to(news.title, news_path(news), :target => "_blank" ) %></td>
      <td><%= news.author %></td>
      <td><%= truncate(news.content, :length => 200).html_safe %></td>
      <td>
        <%= link_to("Edit", edit_admin_news_path(news), :class => "btn btn-warning btn-small") %>
        <%= link_to("Delete", admin_news_path(news), :method => :delete, :confirm => "Are You Sure you want to delete ?", :class => "btn btn-danger btn-small") %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/news/new.html.erb
<div class="span10">
  <h3>Add News</h3>
  <%= simple_form_for([:admin, @news]) do |f| %>
  <%= f.input(:title) %>
  <%= f.input(:author) %>
  <%= f.input(:will_publish_at) %>
  <%= f.input(:content, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_news_index_path, :class => "btn btn-warning") %>
  <% end %>
</div>
<%= tinymce_assets %>
<%= tinymce theme: 'advanced' %>