config/routes.rb
# -*- encoding : utf-8 -*-
RhodesPc2::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'pages#landing'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  match "/pages/glenn", :id => 'glenn'
  match "/pages/heather", :id => 'heather'

  get "/admin" => 'admin/news#index'

  namespace :admin do
    resources :news
    resources :events
    resources :people
  end

  resources :news
  resources :events do
    member do
      get "download"
    end
  end
  resources :people
  
  resources :contacts do
    collection do
      post "send_form_information"
    end
  end
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  title                 :string(255)
#  email                 :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  description_up_right  :text
#  description_down_left :text
#  thumb_photo           :string(255)
#  full_photo            :string(255)
#  url                   :string(255)
#

# -*- encoding : utf-8 -*-
class Person < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name, :title, :email, :thumb_photo, :full_photo, :description_up_right, :description_down_left, :url
  validates_presence_of :name, :title

  mount_uploader :thumb_photo, ThumbUploader
  mount_uploader :full_photo, FullUploader

  acts_as_url :name

  def to_param
    url # or whatever you set :url_attribute to
  end
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < ApplicationController
  layout "admin"
  before_filter :login_required
  before_filter :require_is_admin
  
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])

    if @person.save
      redirect_to admin_people_path, :notice => "Person saved"
    else
      flash[:warning] = "Something went wrong :<"
      render :new
    end
  end

  def edit
    @person = Person.find_by_url(params[:id])
  end

  def update
    @person = Person.find_by_url(params[:id])

    if @person.update_attributes(params[:person])
      redirect_to admin_people_path, :notice => "Person Updated"
    else
      flash[:warning] = "Something went wrong :<"
      render :edit
    end
  end

  def destroy
    @person = Person.find_by_url(params[:id])
    @person.destroy

    redirect_to admin_people_path, :notice => "Person Deleted"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  layout "bio"
  
  def show
    @person = Person.find_by_url(params[:id])
  end
end

app/helpers/admin/people_helper.rb
module Admin::PeopleHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/admin/people/edit.html.erb
<div class="span10">
  <h3>Add Person</h3>
  <%= simple_form_for([:admin, @person], :html => {:multipart => true}) do |f| %>
  <%= f.input(:name) %>
  <%= f.input(:title) %>
  <%= f.input(:email) %>
  <%= f.input(:url, :label => "Page URL") %>
  <%= image_tag(@person.thumb_photo.url) if @person.thumb_photo.present? %>
  <%= f.input(:thumb_photo, :label => "Thumb photo ( 210px x 210px )", :as => :file) %>
  <%= image_tag(@person.full_photo.url) if @person.full_photo.present? %>
  <%= f.input(:full_photo, :label => "Full photo ( 280px x 385px )", :as => :file) %>
  <%= f.input(:description_up_right, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.input(:description_down_left, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_people_path, :class => "btn btn-warning") %>
  <% end %>
</div>
<%= tinymce_assets %>
<%= tinymce theme: 'advanced' %>

app/views/admin/people/index.html.erb
<div class="span10">

  <h3>People List</h3>
  <%= link_to("Add Person", new_admin_person_path, :class => "btn btn-info pull-right") %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="200px">Name</th>
        <th>Email</th>
        <th width="100px">Title</th>
        <th width="120px">Action</th>
      </tr>
    </thead>
    <% @people.each do |person| %>
    <tr>
      <td><%= link_to(person.name, person_path(person), :target => "_blank" ) %></td>
      <td><%= person.email %></td>
      <td><%= person.title %></td>
      <td>
        <%= link_to("Edit", edit_admin_person_path(person), :class => "btn btn-warning btn-small") %>
        <%= link_to("Delete", admin_person_path(person), :method => :delete, :confirm => "Are You Sure you want to delete ?", :class => "btn btn-danger btn-small") %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/people/new.html.erb
<div class="span10">
  <h3>Add Person</h3>
  <%= simple_form_for([:admin, @person], :html => {:multipart => true}) do |f| %>
  <%= f.input(:name) %>
  <%= f.input(:title) %>
  <%= f.input(:email) %>
  <%= f.input(:thumb_photo, :label => "Thumb photo ( 210px x 210px )", :as => :file) %>
  <%= f.input(:full_photo, :label => "Full photo ( 280px x 385px )", :as => :file) %>
  <%= f.input(:description_up_right, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.input(:description_down_left, :input_html => {:class => "tinymce", :style => "width:800px;"}) %>
  <%= f.submit("Save", :class => "btn btn-info") %>
  <%= link_to("Cancel", admin_people_path, :class => "btn btn-warning") %>
  <% end %>
</div>
<%= tinymce_assets %>
<%= tinymce theme: 'advanced' %>