config/routes.rb
# -*- encoding : utf-8 -*-
RhodesPc2::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'pages#landing'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  match "/pages/glenn", :id => 'glenn'
  match "/pages/heather", :id => 'heather'

  get "/admin" => 'admin/news#index'

  namespace :admin do
    resources :news
    resources :events
    resources :people
  end

  resources :news
  resources :events do
    member do
      get "download"
    end
  end
  resources :people
  
  resources :contacts do
    collection do
      post "send_form_information"
    end
  end
end

app/views/common/_admin_sidebar.html.erb
<div class="span2">
  <ul class="sidebar">
    <li><%= link_to("News List", admin_news_index_path, :class => "btn btn-info") %></li>
    <li><%= link_to("Events List", admin_events_path, :class => "btn btn-info") %></li>
    <li><%= link_to("People List", admin_people_path, :class => "btn btn-info") %></li>
    <li><%= link_to("Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-danger") %></li>
  </ul>
</div>

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_contact_us.html.erb
<div class="row">
  <div class="span12" align="center">
    <div class="green caption">Green Office</div>
  </div>
  <div class="span12">
    <h3>Contact Us</h3>
  </div>
  <div class="span6">
    <%= render partial: "common/contact_form" %>
  </div>
  <div class="span3">
    <%= image_tag("tpe_location.png") %>
    <h5><b>Taipei, Taiwan</b></h5>
    <p>Tel/ 886-2-2767-7150</p>
    <p>Fax/ 886-2-2767-9313</p>
    <br>
    <p>No.17, Ln. 155, Sanmin Rd.,</p>
    <p>Songshan Dist., Taipei City 105,</p>
    <p>Taiwan (R.O.C)</p>
  </div>
  <div class="span3">
    <%= image_tag("sf_location.png") %>
    <h5><b>San Francisco, United States</b></h5>
    <p>Tel/ 1-415-293-8185</p>
    <p>Fax/ 1-415-477-4003</p>
    <br>
    <p>One Market Street, Spear Tower,</p>
    <p>Suite 3600, San Francisco,</p>
    <p>California, United States 94105</p>
  </div>
</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <p class="copyright">Copyright @2013 <%= Setting.app_name %> All rights reserved.</p>
</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_hr.html.erb
<div class="span12">
  <hr>
</div>

app/views/common/_news.html.erb
<div class="row">
  <div class="span12">
    <h3>Legal News and Updates <span> - <%= @display_date %></span></h3>
  </div>
  <div class="span12">
    <ul>
      <% @news.each do |news| %>
      <li><%= link_to(news.title, news_path(news), :target => :blank) %></li>
      <% end %>
    </ul>
  </div>
  <div class="span12">
    <%= link_to("more news ...", news_index_path, :class => "pull-right btn btn-info") %>
  </div>
</div>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_people.html.erb
<div class="row">
  <div class="span12">
    <h3>Our People</h3>
  </div>
  <div class="span3">
  </div>
  <% @people.each do |person| %>
    <div class="span3">
      <%= image_tag(person.thumb_photo.url, :width => 210, :height => 210) %>
      <h4><%= link_to(person.name, person_path(person), :target => "_blank") %></h4>
      <p><%= person.title %></p>
    </div>
  <% end %>
</div>

app/views/common/_quote.html.erb
<section class="welcome-message">
  <div class="container">
    <div class="hero-unit">
      <h3>"The secret of getting ahead is getting started." </h3>
      <p class="right">- Mark Twain</p>
    </div>
  </div>
</section>

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_slide.html.erb
<div class="span12">
  <section class="slider">
    <div class="container">
      <div class="well">
        <div id="myCarousel" class="carousel slide">
          <div class="carousel-inner">
            <div class="item active">
              <%= image_tag("slide_0.jpg") %>
              <div class="carousel-caption animation">
                <!-- <h3 data-animate="fadeInLeftBig" class="caption-white animate0" style="opacity: 0;">Fully Responsive Layout</h3>
                <p data-animate="fadeInRightBig" class="caption-white-small animate1" style="opacity: 0;">Sed posuere consectetur est at lobortis.</p> -->
              </div> 
            </div>
            
          </div>
          <!-- Carousel nav -->
          <!-- <a class="carousel-control left" href="#myCarousel" data-slide="prev"><i class="icon-chevron-left"></i></a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next"><i class="icon-chevron-right"></i></a> -->
        </div>
      </div>               
    </div>
  </section>
</div>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">
    <!-- <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
    </li> -->
  <% if current_user %>    
    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>
      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>
    </li>
  <% else %>
    <!-- <li> <%= link_to( "Sign Up" ,new_user_registration_path) %> </li> -->
    <li> <%= link_to( "Login", new_user_session_path )  %> </li>   
    <!-- <li> <%= link_to( "FB Login", "/users/auth/facebook" )  %> </li>    -->
  <% end %>
</ul>